### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by FelipeMunhoz** [Tuntenfisch/Voxels#1]
Is it possible to generate chunks on all axes?

**Comment by Ultdx** [comment]
Yes you can, only the Y axe is missing. 
You can modify the WorldManager.cs file  and replace the int3 CalculateChunkCoordinate variable by 
` private int3 CalculateChunkCoordinate(float3 position) => new int3((int)math.round(position.x / m_chunkDimensions.x), (int)math.round(position.y / m_chunkDimensions.y), (int)math.round(position.z / m_chunkDimensions.z));
`

Also, line ~209 you can add `                EnqueueChunk(chunkCoordinate + new int3(0, 1, 0), viewerPosition);
                EnqueueChunk(chunkCoordinate - new int3(0, 1, 0), viewerPosition);`
for Y axis. It is not optimized in any way, but it works.

**Comment by Tantenfisch** [comment]
Sorry for the late response. What @UnlimitedX said is correct. But especially GPU memory requirements shoot up insanely with this change. All in all the Worldmanager (which is responsible for loading the world around the player) isn't that advanced and sophisticated. You'll probably have to implement your own if you have specific needs.

**Comment by Neovariance** [comment]
in addition I needed to add in DualContouring.Process()
if (VertexCount == 0) return Status.Done;
